# Generated by Django 5.1.1 on 2025-02-05 19:23

import agency.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название тура"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("cz", "Чехия"),
                            ("it", "Италия"),
                            ("is", "Исландия"),
                            ("eg", "Египет"),
                            ("pt", "Португалия"),
                            ("es", "Испания"),
                            ("jo", "Иордания"),
                            ("fr", "Франция"),
                            ("nl", "Нидерланды"),
                            ("no", "Норвегия"),
                        ],
                        max_length=2,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "welcome_message",
                    models.CharField(
                        max_length=255, verbose_name="Приветственное сообщение"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="Длительность (дней)"),
                ),
                (
                    "accommodation",
                    models.TextField(
                        default="По 2 в комнате", verbose_name="Проживание"
                    ),
                ),
                (
                    "group_size",
                    models.PositiveIntegerField(verbose_name="Макс. размер группы"),
                ),
                (
                    "leaders",
                    models.CharField(
                        default="Сопровождение тур-лидером Fiery Trips",
                        max_length=255,
                        verbose_name="Команда",
                    ),
                ),
                (
                    "bonus",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подарки"
                    ),
                ),
                ("ask_title", models.CharField(max_length=60, verbose_name="Вопрос")),
                ("description", models.TextField(verbose_name="Описания тура")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("seo_title", models.CharField(blank=True, max_length=60)),
                ("seo_description", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="agency_trip_title_3e8c87_idx"),
                    models.Index(
                        fields=["country"], name="agency_trip_country_b23808_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="agency_trip_created_3b2bcd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramByDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(default=1, verbose_name="День"),
                ),
                ("title", models.CharField(max_length=60, verbose_name="Место")),
                ("description", models.TextField(verbose_name="Описание дня")),
                (
                    "accommodation",
                    models.TextField(blank=True, verbose_name="Проживание"),
                ),
                (
                    "meal_plan",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Питание"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="agency.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "День тура",
                "verbose_name_plural": "Дни тура",
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="IncludedFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="Пункт")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Иконка (FontAwesome)"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_features",
                        to="agency.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="agency.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TripDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "current_members",
                    models.PositiveIntegerField(verbose_name="Количество брони"),
                ),
                (
                    "is_special_offer",
                    models.BooleanField(default=False, verbose_name="Спецпредложение"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="Иконка офера (FontAwesome)",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_dates",
                        to="agency.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to=agency.models.image_upload_path)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("main", "Главное фото(1)"),
                            ("gallery", "Фото галереи(5)"),
                            ("slide", "Фото с тура(n)"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Подпись"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="agency.trip",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("type", "main")),
                        fields=("trip", "type"),
                        name="unique_main_photo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TripRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("tg", "Telegram"),
                            ("wa", "WhatsApp"),
                            ("call", "Звонок"),
                        ],
                        max_length=4,
                        verbose_name="Способ связи",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_spam", models.BooleanField(default=False)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="agency.trip",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["phone"], name="agency_trip_phone_daab41_idx"),
                    models.Index(
                        fields=["created_at"], name="agency_trip_created_dc7475_idx"
                    ),
                ],
            },
        ),
    ]
