# Generated by Django 5.1.1 on 2025-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("avatar", models.ImageField(upload_to="reviews")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sociallink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="FontAwesome"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.AddField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="accommodation",
            field=models.CharField(
                default="По 2 в комнате", max_length=255, verbose_name="Проживание"
            ),
        ),
    ]
